In [1]:
import pandas as pd
import os
from time import time
from IPython.display import display # Allows the use of display() for DataFrames
import numpy as np
# Import supplementary visualization code visuals.py
#import visuals as vs

# Pretty display for notebooks
%matplotlib inline

### Setting files and directories

In [3]:
path_to_data= "/home/ubuntu/udacity/CodeGladiator/invesco/data"

transaction_file = "Code-Gladiators-Transaction.csv"
#investment_exp_file = "Code-Gladiators-InvestmentExperience.csv"
investment_exp_file = "imputed_investment_exp.csv"
aum_file = "Code-Gladiators-AUM.csv"
activity_file = "Code-Gladiators-Activity.csv"

test_file = "test_data.csv"

### reading csv files into pandas dataframe

In [3]:
transaction_df = pd.read_csv(os.path.join(path_to_data, transaction_file))
investment_exp_df = pd.read_csv(os.path.join(path_to_data, investment_exp_file))
aum_df = pd.read_csv(os.path.join(path_to_data, aum_file))
activity_df = pd.read_csv(os.path.join(path_to_data, activity_file))
test_df = pd.read_csv(os.path.join(path_to_data,test_file))

In [4]:
investment_exp_df.describe()

,Unique_Investment_Id,Rating,1 Yr % Rank,3 Yr % Rank,5 Yr % Rank,10 Yr % Rank,1 Yr Return,3 Yr Return,5 Yr Return,10 Yr Return,1 Yr Excess Return vs Primary Ix,3 Yr Excess Return vs Primary Ix,5 Yr Excess Return vs Primary Ix,10 Yr Excess Return vs Primary Ix,1 Yr Excess Return vs Category Ix,3 Yr Excess Return vs Category Ix,5 Yr Excess Return vs Category Ix,10 Yr Excess Return vs Category Ix,Net Flows,Morningstar_Category_Rating
count,14208.000000,14208.000000,14208.000000,14208.000000,14208.000000,14208.000000,14208.000000,14208.000000,14208.000000,14208.000000,14208.000000,14208.000000,14208.000000,14208.000000,14208.000000,14208.000000,14208.000000,14208.000000,1.420800e+04,14208.000000
mean,11322.412162,2.860079,50.542934,57.890484,60.288570,50.948972,0.505751,4.838298,6.333972,5.198885,-2.447895,-2.455915,-2.186208,-0.678274,-1.094067,-1.614811,-1.364869,-0.672600,-6.377975e+07,2.880068
std,6191.457480,1.048008,30.098916,29.092544,24.642931,19.876886,9.387634,6.036643,4.709164,1.650218,7.374441,4.902257,4.017693,1.488412,5.575717,3.092775,2.118007,1.129918,2.481486e+09,0.716016
min,3425.000000,1.000000,1.000000,1.000000,1.000000,1.000000,-42.193310,-31.087397,-22.446858,-5.599918,-53.109905,-45.179073,-35.878603,-12.082922,-25.578430,-14.144617,-11.795999,-5.766622,-1.297583e+10,1.000000
25%,4204.500000,2.000000,24.000000,33.000000,46.000000,51.000000,-4.312881,2.007149,4.806016,5.205071,-5.019650,-3.721925,-2.424244,-0.600988,-3.277456,-3.018389,-2.259560,-0.696837,-7.153228e+08,2.000000
50%,11556.500000,3.000000,52.000000,63.000000,65.000000,51.000000,1.208245,4.433606,6.127918,5.205071,-1.669335,-1.552324,-1.569317,-0.600988,-0.892722,-1.325126,-1.263603,-0.696837,-4.787134e+07,3.000000
75%,18211.250000,3.000000,78.000000,84.000000,78.000000,51.000000,5.956346,7.591096,8.330664,5.205071,0.457572,-0.143556,-0.898224,-0.600988,1.047254,0.130718,-0.406703,-0.696837,3.027055e+08,3.000000
max,20064.000000,5.000000,100.000000,100.000000,100.000000,100.000000,92.880240,30.120821,23.354639,12.873699,87.266266,15.049113,11.611675,5.294308,81.410878,13.316988,7.225122,5.224587,1.894229e+10,5.000000

In [5]:
test_df.head()

   Unique_Advisor_Id  Unique_Investment_Id
0            1000103                 14147
1            1000103                  3534
2            1000103                  3651
3            1000103                  7668
4            1000103                  9339

### processing data

Grouping data by unique advisor id and month. Final output will store sums of the assets under managements and shares for each advisor in particular month

In [4]:
grouped_advisor_aum_df = aum_df.groupby(['Unique_Advisor_Id','Month']).agg({'AUM': 'sum','Shares':'sum','Unique_Investment_Id':'count'}).reset_index().rename(columns={'Unique_Investment_Id':'Counts'})
grouped_advisor_aum_df.head()

   Unique_Advisor_Id      Month         Shares  Counts           AUM
0              12243  2016 / 01  109673.678500      44  1.461389e+06
1              12243  2016 / 02  106252.324833      44  1.414581e+06
2              12243  2016 / 03  103253.896694      44  1.426161e+06
3              12243  2016 / 04  100449.798917      44  1.414247e+06
4              12243  2016 / 05   91960.177528      44  1.241367e+06

Grouping data by unique investment vehicle id and month. Final output will store sums of the assets under managements and shares for each investment vehicle in particular month

In [5]:
grouped_investment_aum_df = aum_df.groupby(['Unique_Investment_Id','Month']).agg({'AUM': 'sum','Shares':'sum','Unique_Advisor_Id':'count'}).reset_index().rename(columns={'Unique_Advisor_Id':'Counts'})
grouped_investment_aum_df[grouped_investment_aum_df['Unique_Investment_Id'] == 3425].head()

     Unique_Investment_Id      Month        Shares            AUM  Counts
656                  3425  2016 / 01  28135.758333  515757.171333      36
657                  3425  2016 / 02  28135.758333  509040.019833      36
658                  3425  2016 / 03  27256.321667  540765.421500      36
659                  3425  2016 / 04  26081.948333  532694.127833      39
660                  3425  2016 / 05  12041.815000  247218.462500      38

Splitting Month column to take out month only for help in joining with different dataframes

In [6]:
grouped_investment_aum_df['Year'],grouped_investment_aum_df['Month']=grouped_investment_aum_df['Month'].str.split(' /', 1).str
grouped_advisor_aum_df['Year'],grouped_advisor_aum_df['Month']=grouped_advisor_aum_df['Month'].str.split(' /', 1).str

transaction_df['Year'],transaction_df['Month']=transaction_df['Month'].str.split(' /', 1).str
investment_exp_df['Year'],investment_exp_df['Month']=investment_exp_df['Month'].str.split(' /', 1).str
aum_df['Year'],aum_df['Month']=aum_df['Month'].str.split(' /', 1).str
activity_df['Year'],activity_df['Month']=activity_df['Month'].str.split(' /', 1).str

In [8]:
transaction_df.head()

,Unique_Advisor_Id,Unique_Investment_Id,Month,Transaction_Type,Code_1,Code_2,Code_3,Code_4,Code_5,Amount,Year
0,1000103,20058,01,P,1,48,1,7,4,4678.666667,2016
1,1000103,20058,01,P,1,48,1,7,4,353.066667,2016
2,1000103,20058,01,P,1,48,1,7,4,1809.626667,2016
3,1000103,20058,02,P,1,48,1,7,4,4678.666667,2016
4,1000103,20058,02,P,1,48,1,7,4,353.066667,2016

Incerementing each Month with 1 so corresponding row can be mapped with transactions. Current month transaction is result of previous month experience/AUM/Shares

In [7]:
grouped_investment_aum_df['Mapping_Month']= grouped_investment_aum_df['Month'].astype(int).apply(lambda x : x+1)
grouped_advisor_aum_df['Mapping_Month']= grouped_advisor_aum_df['Month'].astype(int).apply(lambda x : x+1)
investment_exp_df['Mapping_Month']= investment_exp_df['Month'].astype(int).apply(lambda x : x+1)
aum_df['Mapping_Month']= aum_df['Month'].astype(int).apply(lambda x : x+1)
activity_df['Mapping_Month']= activity_df['Month'].astype(int).apply(lambda x : x+1)


grouped_investment_aum_df.head()

,Unique_Investment_Id,Month,Shares,AUM,Counts,Year,Mapping_Month
0,74,01,376166.733333,376166.733333,3,2016,2
1,74,02,376166.733333,376166.733333,3,2016,3
2,74,03,376172.733333,376172.733333,3,2016,4
3,74,04,376175.733333,376175.733333,3,2016,5
4,74,05,376178.833333,376178.833333,3,2016,6

Converting month in transaction history to integer to ease in join operations

In [8]:
transaction_df['Month'] =  transaction_df['Month'].astype(int).apply(lambda x : x+0)

transaction_df.head()

,Unique_Advisor_Id,Unique_Investment_Id,Month,Transaction_Type,Code_1,Code_2,Code_3,Code_4,Code_5,Amount,Year
0,1000103,20058,1,P,1,48,1,7,4,4678.666667,2016
1,1000103,20058,1,P,1,48,1,7,4,353.066667,2016
2,1000103,20058,1,P,1,48,1,7,4,1809.626667,2016
3,1000103,20058,2,P,1,48,1,7,4,4678.666667,2016
4,1000103,20058,2,P,1,48,1,7,4,353.066667,2016

In [9]:
final_transaction = pd.merge(transaction_df, grouped_investment_aum_df, left_on=["Month","Unique_Investment_Id"],right_on=["Mapping_Month","Unique_Investment_Id"], how="left") 
final_transaction = final_transaction.rename(columns={'Month_x': 'Month', 'AUM': 'AUM_investor','Year_x' : 'Year', 'Counts' : 'Counts_investor', 'Shares': 'Shares_investor','Month_y':'Month_actual'})
final_transaction = final_transaction.drop('Year_y', 1)
final_transaction.head()

,Unique_Advisor_Id,Unique_Investment_Id,Month,Transaction_Type,Code_1,Code_2,Code_3,Code_4,Code_5,Amount,Year,Month_actual,Shares_investor,AUM_investor,Counts_investor,Mapping_Month
0,1000103,20058,1,P,1,48,1,7,4,4678.666667,2016,NaN,NaN,NaN,NaN,NaN
1,1000103,20058,1,P,1,48,1,7,4,353.066667,2016,NaN,NaN,NaN,NaN,NaN
2,1000103,20058,1,P,1,48,1,7,4,1809.626667,2016,NaN,NaN,NaN,NaN,NaN
3,1000103,20058,2,P,1,48,1,7,4,4678.666667,2016,01,132979.907,1.339674e+06,2.0,2.0
4,1000103,20058,2,P,1,48,1,7,4,353.066667,2016,01,132979.907,1.339674e+06,2.0,2.0

In [10]:
test_transaction = pd.merge(test_df, grouped_investment_aum_df[grouped_investment_aum_df["Mapping_Month"]== 13], on="Unique_Investment_Id", how="left")
test_transaction = test_transaction.rename(columns={ 'AUM': 'AUM_investor','Counts' : 'Counts_investor', 'Shares': 'Shares_investor'})

test_transaction.shape

(8714, 8)

In [346]:
 test_transaction[test_transaction['AUM_investor'].isnull()]

,Unique_Advisor_Id,Unique_Investment_Id,Month,AUM_investor,Shares_investor,Counts_investor,Year,Mapping_Month
9,1000533,5538,NaN,NaN,NaN,NaN,NaN,NaN
107,1009195,15354,NaN,NaN,NaN,NaN,NaN,NaN
125,1009570,18381,NaN,NaN,NaN,NaN,NaN,NaN
128,1009570,5841,NaN,NaN,NaN,NaN,NaN,NaN
279,1018491,15241,NaN,NaN,NaN,NaN,NaN,NaN
280,1018491,3840,NaN,NaN,NaN,NaN,NaN,NaN
281,1018491,3842,NaN,NaN,NaN,NaN,NaN,NaN
289,1018509,12488,NaN,NaN,NaN,NaN,NaN,NaN
421,1021356,17883,NaN,NaN,NaN,NaN,NaN,NaN
422,1021356,18551,NaN,NaN,NaN,NaN,NaN,NaN
425,1021356,6809,NaN,NaN,NaN,NaN,NaN,NaN
427,1021942,14554,NaN,NaN,NaN,NaN,NaN,NaN
428,1021942,18178,NaN,NaN,NaN,NaN,NaN,NaN
429,1021942,18784,NaN,NaN,NaN,NaN,NaN,NaN
489,1022063,16448,NaN,NaN,NaN,NaN,NaN,NaN
490,1022063,18178,NaN,NaN,NaN,NaN,NaN,NaN
499,1022088,16448,NaN,NaN,NaN,NaN,NaN,NaN
500,1022088,18178,NaN,NaN,NaN,NaN,NaN,NaN
532,1022158,18178,NaN,NaN,NaN,NaN,NaN,NaN
542,1022191,17883,NaN,NaN,NaN,NaN,NaN,NaN
543,1022191,18551,NaN,NaN,NaN,NaN,NaN,NaN
544,1022191,6809,NaN,NaN,NaN,NaN,NaN,NaN
561,1022961,9638,NaN,NaN,NaN,NaN,NaN,NaN
568,1022980,18178,NaN,NaN,NaN,NaN,NaN,NaN
632,1024140,9938,NaN,NaN,NaN,NaN,NaN,NaN
718,1030542,16446,NaN,NaN,NaN,NaN,NaN,NaN
719,1030542,16448,NaN,NaN,NaN,NaN,NaN,NaN
724,1030542,6461,NaN,NaN,NaN,NaN,NaN,NaN
725,1030542,9145,NaN,NaN,NaN,NaN,NaN,NaN
791,1031195,6807,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
7960,974374,8314,NaN,NaN,NaN,NaN,NaN,NaN
7971,974892,11535,NaN,NaN,NaN,NaN,NaN,NaN
8103,980340,6461,NaN,NaN,NaN,NaN,NaN,NaN
8106,980351,16448,NaN,NaN,NaN,NaN,NaN,NaN
8107,980351,18178,NaN,NaN,NaN,NaN,NaN,NaN
8110,980351,6807,NaN,NaN,NaN,NaN,NaN,NaN
8167,986453,12488,NaN,NaN,NaN,NaN,NaN,NaN
8168,986453,18213,NaN,NaN,NaN,NaN,NaN,NaN
8253,987898,12488,NaN,NaN,NaN,NaN,NaN,NaN
8303,988198,4514,NaN,NaN,NaN,NaN,NaN,NaN
8410,991359,17883,NaN,NaN,NaN,NaN,NaN,NaN
8411,991359,18551,NaN,NaN,NaN,NaN,NaN,NaN
8415,991359,6809,NaN,NaN,NaN,NaN,NaN,NaN
8419,991479,16448,NaN,NaN,NaN,NaN,NaN,NaN
8429,991481,3842,NaN,NaN,NaN,NaN,NaN,NaN
8437,991526,18549,NaN,NaN,NaN,NaN,NaN,NaN
8457,991595,16448,NaN,NaN,NaN,NaN,NaN,NaN
8458,991595,18178,NaN,NaN,NaN,NaN,NaN,NaN
8459,991595,18784,NaN,NaN,NaN,NaN,NaN,NaN
8475,991613,18178,NaN,NaN,NaN,NaN,NaN,NaN
8482,991613,6460,NaN,NaN,NaN,NaN,NaN,NaN
8483,991613,6461,NaN,NaN,NaN,NaN,NaN,NaN
8484,991613,6807,NaN,NaN,NaN,NaN,NaN,NaN
8485,991613,9738,NaN,NaN,NaN,NaN,NaN,NaN
8698,999483,14691,NaN,NaN,NaN,NaN,NaN,NaN
8701,999483,3840,NaN,NaN,NaN,NaN,NaN,NaN
8702,999483,3841,NaN,NaN,NaN,NaN,NaN,NaN
8707,999483,5248,NaN,NaN,NaN,NaN,NaN,NaN
8708,999483,5839,NaN,NaN,NaN,NaN,NaN,NaN
8709,999483,5841,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
final_transaction = pd.merge(final_transaction, grouped_advisor_aum_df, left_on=["Month","Unique_Advisor_Id"],right_on=["Mapping_Month","Unique_Advisor_Id"], how="left") 
final_transaction = final_transaction.rename(columns={'Month_x': 'Month', 'AUM': 'AUM_advisor','Year_x' : 'Year', 'Counts' : 'Counts_advisor', 'Shares': 'Shares_advisor','Mapping_Month_x': 'Mapping_Month'})
final_transaction = final_transaction.drop(['Year_y','Mapping_Month_y','Month_y'], 1)

final_transaction.head()

,Unique_Advisor_Id,Unique_Investment_Id,Month,Transaction_Type,Code_1,Code_2,Code_3,Code_4,Code_5,Amount,Year,Month_actual,Shares_investor,AUM_investor,Counts_investor,Mapping_Month,Shares_advisor,Counts_advisor,AUM_advisor
0,1000103,20058,1,P,1,48,1,7,4,4678.666667,2016,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1000103,20058,1,P,1,48,1,7,4,353.066667,2016,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1000103,20058,1,P,1,48,1,7,4,1809.626667,2016,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1000103,20058,2,P,1,48,1,7,4,4678.666667,2016,01,132979.907,1.339674e+06,2.0,2.0,13536.409,6.0,245350.665667
4,1000103,20058,2,P,1,48,1,7,4,353.066667,2016,01,132979.907,1.339674e+06,2.0,2.0,13536.409,6.0,245350.665667

In [12]:
test_transaction = pd.merge(test_transaction, grouped_advisor_aum_df[grouped_advisor_aum_df["Mapping_Month"]== 13], on="Unique_Advisor_Id", how="left")

test_transaction = test_transaction.rename(columns={ 'AUM': 'AUM_advisor','Counts' : 'Counts_advisor', 'Shares': 'Shares_advisor','Month_x':'Month','Mapping_Month_x':'Mapping_Month'})
test_transaction = test_transaction.drop(['Year_x','Year_y','Mapping_Month_y','Month_y','Mapping_Month'], 1)

test_transaction.shape

(8714, 9)

In [13]:
print(investment_exp_df.shape)
investment_exp_df= investment_exp_df[investment_exp_df['Year']=='2016']
investment_exp_df.shape

(14208, 25)

(7104, 25)

In [14]:
final_transaction_with_exp = pd.merge(final_transaction, investment_exp_df, left_on=["Month","Unique_Investment_Id"],right_on=["Mapping_Month","Unique_Investment_Id"], how="left") 
final_transaction_with_exp = final_transaction_with_exp.rename(columns={'Month_x': 'Month', 'AUM': 'AUM_advisor','Year_x' : 'Year', 'Mapping_Month_x':'Mapping_Month'})
final_transaction_with_exp = final_transaction_with_exp.drop(['Year_y','Mapping_Month_y','Month_y'], 1)

final_transaction_with_exp.head()

,Unique_Advisor_Id,Unique_Investment_Id,Month,Transaction_Type,Code_1,Code_2,Code_3,Code_4,Code_5,Amount,...,1 Yr Excess Return vs Primary Ix,3 Yr Excess Return vs Primary Ix,5 Yr Excess Return vs Primary Ix,10 Yr Excess Return vs Primary Ix,1 Yr Excess Return vs Category Ix,3 Yr Excess Return vs Category Ix,5 Yr Excess Return vs Category Ix,10 Yr Excess Return vs Category Ix,Net Flows,Morningstar_Category_Rating
0,1000103,20058,1,P,1,48,1,7,4,4678.666667,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1000103,20058,1,P,1,48,1,7,4,353.066667,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1000103,20058,1,P,1,48,1,7,4,1809.626667,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1000103,20058,2,P,1,48,1,7,4,4678.666667,...,-15.184451,-9.429957,-1.569317,-0.600988,-10.850458,-6.919882,-1.263603,-0.696837,-1.618909e+09,3.0
4,1000103,20058,2,P,1,48,1,7,4,353.066667,...,-15.184451,-9.429957,-1.569317,-0.600988,-10.850458,-6.919882,-1.263603,-0.696837,-1.618909e+09,3.0

In [15]:
final_transaction_with_exp.columns.values.tolist()

['Unique_Advisor_Id',
 'Unique_Investment_Id',
 'Month',
 'Transaction_Type',
 'Code_1',
 'Code_2',
 'Code_3',
 'Code_4',
 'Code_5',
 'Amount',
 'Year',
 'Month_actual',
 'Shares_investor',
 'AUM_investor',
 'Counts_investor',
 'Mapping_Month',
 'Shares_advisor',
 'Counts_advisor',
 'AUM_advisor',
 'Morningstar Category',
 'Investment',
 'Rating',
 '1 Yr % Rank',
 '3 Yr % Rank',
 '5 Yr % Rank',
 '10 Yr % Rank',
 '1 Yr Return',
 '3 Yr Return',
 '5 Yr Return',
 '10 Yr Return',
 '1 Yr Excess Return vs Primary Ix',
 '3 Yr Excess Return vs Primary Ix',
 '5 Yr Excess Return vs Primary Ix',
 '10 Yr Excess Return vs Primary Ix',
 '1 Yr Excess Return vs Category Ix',
 '3 Yr Excess Return vs Category Ix',
 '5 Yr Excess Return vs Category Ix',
 '10 Yr Excess Return vs Category Ix',
 'Net Flows',
 'Morningstar_Category_Rating']

In [16]:
test_transaction_with_exp = pd.merge(test_transaction, investment_exp_df[investment_exp_df["Mapping_Month"]== 13 ], on="Unique_Investment_Id", how="left")

test_transaction_with_exp.shape

(8714, 33)

In [19]:
test_transaction_with_exp.columns.values.tolist()

['Unique_Advisor_Id',
 'Unique_Investment_Id',
 'Month_x',
 'Counts_investor',
 'AUM_investor',
 'Shares_investor',
 'Counts_advisor',
 'AUM_advisor',
 'Shares_advisor',
 'Morningstar Category',
 'Month_y',
 'Investment',
 'Rating',
 '1 Yr % Rank',
 '3 Yr % Rank',
 '5 Yr % Rank',
 '10 Yr % Rank',
 '1 Yr Return',
 '3 Yr Return',
 '5 Yr Return',
 '10 Yr Return',
 '1 Yr Excess Return vs Primary Ix',
 '3 Yr Excess Return vs Primary Ix',
 '5 Yr Excess Return vs Primary Ix',
 '10 Yr Excess Return vs Primary Ix',
 '1 Yr Excess Return vs Category Ix',
 '3 Yr Excess Return vs Category Ix',
 '5 Yr Excess Return vs Category Ix',
 '10 Yr Excess Return vs Category Ix',
 'Net Flows',
 'Morningstar_Category_Rating',
 'Year',
 'Mapping_Month']

In [17]:

#log_columns= ['AUM_investor','Shares_investor','AUM_advisor','Shares_advisor','Rating','1 Yr % Rank','3 Yr % Rank','10 Yr % Rank','1 Yr Return','3 Yr Return','5 Yr Return','10 Yr Return','1 Yr Excess Return vs Primary Ix','3 Yr Excess Return vs Primary Ix','1 Yr Excess Return vs Category Ix','3 Yr Excess Return vs Category Ix']

#for column in log_columns:
#    final_transaction_with_exp[column+'_log'] = np.log(final_transaction_with_exp[column])
#    test_transaction_with_exp[column+'_log'] = np.log(test_transaction_with_exp[column])

final_transaction_with_exp['AUM_investor_log'] = np.log(final_transaction_with_exp['AUM_investor'])
final_transaction_with_exp['Shares_investor_log'] = np.log(final_transaction_with_exp['Shares_investor'])

final_transaction_with_exp['AUM_advisor_log'] = np.log(final_transaction_with_exp['AUM_advisor'])
final_transaction_with_exp['Shares_advisor_log'] = np.log(final_transaction_with_exp['Shares_advisor'])


test_transaction_with_exp['AUM_investor_log'] = np.log(test_transaction_with_exp['AUM_investor'])
test_transaction_with_exp['Shares_investor_log'] = np.log(test_transaction_with_exp['Shares_investor'])

test_transaction_with_exp['AUM_advisor_log'] = np.log(test_transaction_with_exp['AUM_advisor'])
test_transaction_with_exp['Shares_advisor_log'] = np.log(test_transaction_with_exp['Shares_advisor'])



final_transaction_with_exp= final_transaction_with_exp.dropna()

/home/ubuntu/.local/lib/python3.5/site-packages/ipykernel/__main__.py:9: RuntimeWarning: divide by zero encountered in log
/home/ubuntu/.local/lib/python3.5/site-packages/ipykernel/__main__.py:11: RuntimeWarning: divide by zero encountered in log
/home/ubuntu/.local/lib/python3.5/site-packages/ipykernel/__main__.py:12: RuntimeWarning: divide by zero encountered in log
/home/ubuntu/.local/lib/python3.5/site-packages/ipykernel/__main__.py:16: RuntimeWarning: divide by zero encountered in log
/home/ubuntu/.local/lib/python3.5/site-packages/ipykernel/__main__.py:19: RuntimeWarning: divide by zero encountered in log

In [18]:
final_transaction_with_exp.apply(lambda x: sum(x.isnull()),axis=0)

Unique_Advisor_Id                     0
Unique_Investment_Id                  0
Month                                 0
Transaction_Type                      0
Code_1                                0
Code_2                                0
Code_3                                0
Code_4                                0
Code_5                                0
Amount                                0
Year                                  0
Month_actual                          0
Shares_investor                       0
AUM_investor                          0
Counts_investor                       0
Mapping_Month                         0
Shares_advisor                        0
Counts_advisor                        0
AUM_advisor                           0
Morningstar Category                  0
Investment                            0
Rating                                0
1 Yr % Rank                           0
3 Yr % Rank                           0
5 Yr % Rank                           0
10 Yr % Rank                          0
1 Yr Return                           0
3 Yr Return                           0
5 Yr Return                           0
10 Yr Return                          0
1 Yr Excess Return vs Primary Ix      0
3 Yr Excess Return vs Primary Ix      0
5 Yr Excess Return vs Primary Ix      0
10 Yr Excess Return vs Primary Ix     0
1 Yr Excess Return vs Category Ix     0
3 Yr Excess Return vs Category Ix     0
5 Yr Excess Return vs Category Ix     0
10 Yr Excess Return vs Category Ix    0
Net Flows                             0
Morningstar_Category_Rating           0
AUM_investor_log                      0
Shares_investor_log                   0
AUM_advisor_log                       0
Shares_advisor_log                    0
dtype: int64

In [23]:
test_transaction_with_exp.apply(lambda x: sum(x.isnull()),axis=0)

Unique_Advisor_Id                       0
Unique_Investment_Id                    0
Month_x                               353
AUM_investor                          353
Counts_investor                       353
Shares_investor                       353
Counts_advisor                        975
AUM_advisor                           975
Shares_advisor                        975
Morningstar Category                  433
Month_y                               433
Investment                            433
Rating                                433
1 Yr % Rank                           433
3 Yr % Rank                           433
5 Yr % Rank                           433
10 Yr % Rank                          433
1 Yr Return                           433
3 Yr Return                           433
5 Yr Return                           433
10 Yr Return                          433
1 Yr Excess Return vs Primary Ix      433
3 Yr Excess Return vs Primary Ix      433
5 Yr Excess Return vs Primary Ix      433
10 Yr Excess Return vs Primary Ix     433
1 Yr Excess Return vs Category Ix     433
3 Yr Excess Return vs Category Ix     433
5 Yr Excess Return vs Category Ix     433
10 Yr Excess Return vs Category Ix    433
Net Flows                             433
Morningstar_Category_Rating           433
Year                                  433
Mapping_Month                         433
AUM_investor_log                      353
Shares_investor_log                   353
AUM_advisor_log                       975
Shares_advisor_log                    975
dtype: int64

In [19]:
#column_list= ['AUM_investor_log','Counts_investor','Shares_investor_log','AUM_advisor_log','Shares_advisor_log','Rating','1 Yr % Rank','3 Yr % Rank','1 Yr Return','3 Yr Return','5 Yr Return','1 Yr Excess Return vs Primary Ix','3 Yr Excess Return vs Primary Ix','1 Yr Excess Return vs Category Ix','3 Yr Excess Return vs Category Ix','Net Flows','Transaction_Type'])
column_list= ['AUM_investor_log','Counts_investor','Shares_investor_log','AUM_advisor_log','Shares_advisor_log','Rating','1 Yr % Rank','3 Yr % Rank','1 Yr Return','3 Yr Return','Net Flows','Morningstar_Category_Rating','Transaction_Type']

#column_list= ['AUM_investor_log','Counts_investor','Shares_investor_log','AUM_advisor_log','Shares_advisor_log','Rating','1 Yr % Rank','3 Yr % Rank','1 Yr Return','3 Yr Return','5 Yr Return','1 Yr Excess Return vs Primary Ix','3 Yr Excess Return vs Primary Ix','1 Yr Excess Return vs Category Ix','3 Yr Excess Return vs Category Ix','Net Flows','Transaction_Type']

In [26]:
final_transaction_with_exp.to_csv("../data/training_transaction_data.csv")

In [20]:
required_train_df = final_transaction_with_exp.filter(column_list)

In [21]:
required_train_df.head()

,AUM_investor_log,Counts_investor,Shares_investor_log,AUM_advisor_log,Shares_advisor_log,Rating,1 Yr % Rank,3 Yr % Rank,1 Yr Return,3 Yr Return,Net Flows,Morningstar_Category_Rating,Transaction_Type
3,14.107937,2.0,11.797953,12.410444,9.513138,1.0,99.0,98.0,-15.849760,1.871172,-1.618909e+09,3.0,P
4,14.107937,2.0,11.797953,12.410444,9.513138,1.0,99.0,98.0,-15.849760,1.871172,-1.618909e+09,3.0,P
5,14.107937,2.0,11.797953,12.410444,9.513138,1.0,99.0,98.0,-15.849760,1.871172,-1.618909e+09,3.0,P
6,14.124399,2.0,11.798241,11.725969,8.683200,1.0,98.0,98.0,-19.845355,2.276382,-7.119961e+08,3.0,P
7,14.124399,2.0,11.798241,11.725969,8.683200,1.0,98.0,98.0,-19.845355,2.276382,-7.119961e+08,3.0,P

In [22]:
required_train_df['Transaction_Type']= required_train_df.apply(lambda x: 0 if x['Transaction_Type']== 'P' else 1, axis=1)

In [30]:
test_transaction_with_exp.to_csv("../data/test_transaction.csv")

In [23]:
required_test_df = test_transaction_with_exp.filter(column_list)

#print(required_test_df[required_test_df['AUM_investor'].isnull()])

#required_test_df=required_test_df.fillna(0)
required_test_df.shape

(8714, 12)

In [26]:
required_train_df.count()

AUM_investor_log               125202
Counts_investor                125202
Shares_investor_log            125202
AUM_advisor_log                125202
Shares_advisor_log             125202
Rating                         125202
1 Yr % Rank                    125202
3 Yr % Rank                    125202
1 Yr Return                    125202
3 Yr Return                    125202
Net Flows                      125202
Morningstar_Category_Rating    125202
Transaction_Type               125202
dtype: int64

In [24]:
required_test_df['Rating'] = required_test_df['Rating'].astype(float)

In [25]:
required_test_df=required_test_df.fillna(required_test_df.median())

In [26]:
required_test_df.count()

AUM_investor_log               8714
Counts_investor                8714
Shares_investor_log            8714
AUM_advisor_log                8714
Shares_advisor_log             8714
Rating                         8714
1 Yr % Rank                    8714
3 Yr % Rank                    8714
1 Yr Return                    8714
3 Yr Return                    8714
Net Flows                      8714
Morningstar_Category_Rating    8714
dtype: int64

In [27]:
# Split the data into features and target label
transaction_type = required_train_df['Transaction_Type']
features_raw = required_train_df.drop('Transaction_Type', axis = 1)
test_raw = required_test_df

In [151]:
print(column_list)

['AUM_investor_log', 'Counts_investor', 'Shares_investor_log', 'AUM_advisor_log', 'Shares_advisor_log', 'Rating', '1 Yr % Rank', '3 Yr % Rank', '1 Yr Return', '3 Yr Return', 'Net Flows', 'Morningstar_Category_Rating', 'Transaction_Type']

In [240]:
# Import sklearn.preprocessing.StandardScaler
from sklearn.preprocessing import MinMaxScaler

# Initialize a scaler, then apply it to the features
scaler = MinMaxScaler()
numerical = ['AUM_investor_log','Counts_investor','Shares_investor_log','AUM_advisor_log','Shares_advisor_log','Rating','1 Yr % Rank','3 Yr % Rank','1 Yr Return','3 Yr Return','Net Flows']

features_raw[numerical] = scaler.fit_transform(required_train_df[numerical])

#test_raw[numerical] = scaler.fit_transform(required_test_df[numerical])
# Show an example of a record with scaling applied
display(features_raw.head(n = 5))

ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

In [28]:
from sklearn.preprocessing import LabelEncoder
var_mod = column_list
var_mod.remove('Transaction_Type')
le = LabelEncoder()
for i in var_mod:
    print(i)
    features_raw[i] = le.fit_transform(features_raw[i])
features_raw.dtypes

AUM_investor_log
Counts_investor
Shares_investor_log
AUM_advisor_log
Shares_advisor_log
Rating
1 Yr % Rank
3 Yr % Rank
1 Yr Return
3 Yr Return
Net Flows
Morningstar_Category_Rating

AUM_investor_log               int64
Counts_investor                int64
Shares_investor_log            int64
AUM_advisor_log                int64
Shares_advisor_log             int64
Rating                         int64
1 Yr % Rank                    int64
3 Yr % Rank                    int64
1 Yr Return                    int64
3 Yr Return                    int64
Net Flows                      int64
Morningstar_Category_Rating    int64
dtype: object

In [29]:
var_mod = column_list
#var_mod.remove('Transaction_Type')
le = LabelEncoder()
for i in var_mod:
    print(i)
    test_raw[i] = le.fit_transform(test_raw[i])
test_raw.dtypes

AUM_investor_log
Counts_investor
Shares_investor_log
AUM_advisor_log
Shares_advisor_log
Rating
1 Yr % Rank
3 Yr % Rank
1 Yr Return
3 Yr Return
Net Flows
Morningstar_Category_Rating

AUM_investor_log               int64
Counts_investor                int64
Shares_investor_log            int64
AUM_advisor_log                int64
Shares_advisor_log             int64
Rating                         int64
1 Yr % Rank                    int64
3 Yr % Rank                    int64
1 Yr Return                    int64
3 Yr Return                    int64
Net Flows                      int64
Morningstar_Category_Rating    int64
dtype: object

In [370]:
test_raw.head()

,AUM_investor_log,Counts_investor,Shares_investor_log,AUM_advisor_log,Shares_advisor_log,Rating,1 Yr % Rank,3 Yr % Rank,1 Yr Return,3 Yr Return,Net Flows,Morningstar_Category_Rating
0,265,139,249,443,721,4,42,5,214,260,5,1
1,157,25,110,443,721,2,19,61,235,227,5,1
2,121,14,82,443,721,2,38,37,16,23,9,2
3,235,95,230,443,721,4,0,2,143,108,22,2
4,110,26,64,443,721,3,41,28,168,205,12,2

In [ ]:
# Produce a scatter matrix for each pair of features in the data

pd.scatter_matrix(features_raw, alpha = 0.3, figsize = (14,8), diagonal = 'kde');

In [62]:
# TODO: One-hot encode the 'features_raw' data using pandas.get_dummies()
features_raw.Rating = features_raw.Rating.astype(str)
test_raw.Rating = test_raw.Rating.astype(str)

features_raw.Morningstar_Category_Rating = features_raw.Morningstar_Category_Rating.astype(str)
test_raw.Morningstar_Category_Rating = test_raw.Morningstar_Category_Rating.astype(str)

features = pd.get_dummies(features_raw)
#test = pd.get_dummies(test_raw)

# TODO: Encode the 'income_raw' data to numerical values
#transaction_type = transaction_type.replace(['P','R'],[0,1])

# Print the number of features after one-hot encoding
encoded_train = list(features.columns)
#encoded_test = list(test.columns)
print ("{} total features after one-hot encoding.".format(len(encoded_train)))
#print ("{} total test features after one-hot encoding.".format(len(encoded_test)))


#Uncomment the following line to see the encoded feature names
#print (encoded)

TypeError: Cannot compare types 'ndarray(dtype=int64)' and 'str'

In [30]:
required_train_df['Transaction_Type'].head()

3    0
4    0
5    0
6    0
7    0
Name: Transaction_Type, dtype: int64

In [34]:
transaction_type.describe()

count    125202.000000
mean          0.620070
std           0.485371
min           0.000000
25%           0.000000
50%           1.000000
75%           1.000000
max           1.000000
Name: Transaction_Type, dtype: float64

In [31]:
# Import train_test_split
from sklearn.cross_validation import train_test_split

# Split the 'features' and 'transaction_type' data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(features_raw, transaction_type, test_size = 0.2, random_state = 0)

# Show the results of the split
print ("Training set has {} samples.".format(X_train.shape[0]))
print ("Testing set has {} samples.".format(X_test.shape[0]))

Training set has 100161 samples.
Testing set has 25041 samples.

/home/ubuntu/.local/lib/python3.5/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)

In [32]:
# TODO: Import two metrics from sklearn - fbeta_score and accuracy_score
from sklearn.metrics import fbeta_score, accuracy_score
# time.time() return time in seconds since the Epoch
from time import time

beta = 0.5

def train_predict(learner, sample_size, X_train, y_train, X_test, y_test): 
    '''
    inputs:
       - learner: the learning algorithm to be trained and predicted on
       - sample_size: the size of samples (number) to be drawn from training set
       - X_train: features training set
       - y_train: income training set
       - X_test: features testing set
       - y_test: income testing set
    '''
    
    results = {}
    
    # TODO: Fit the learner to the training data using slicing with 'sample_size'
    X_train = X_train[:sample_size]
    y_train = y_train[:sample_size]
    
    start = time() # Get start time
    learner.fit(X_train, y_train)
    end = time() # Get end time
    
    # TODO: Calculate the training time
    results['train_time'] = end - start
        
    # TODO: Get the predictions on the test set,
    #       then get predictions on the first 300 training samples
    start = time() # Get start time
    predictions_test = learner.predict(X_test)
    predictions_train = learner.predict(X_train)
    end = time() # Get end time
    
    # TODO: Calculate the total prediction time
    results['pred_time'] = end-start
            
    # TODO: Compute accuracy on the first 300 training samples
    results['acc_train'] = accuracy_score(y_train, predictions_train)
        
    # TODO: Compute accuracy on test set
    results['acc_test'] = accuracy_score(y_test, predictions_test)
    
    # TODO: Compute F-score on the the first 300 training samples
    results['f_train'] = fbeta_score(y_train, predictions_train, beta=beta)
        
   # TODO: Compute F-score on the test set
    results['f_test'] = fbeta_score(y_test, predictions_test, beta=beta)
       
    # Success
    print ("{} trained on {} samples.".format(learner.__class__.__name__, sample_size))
        
    # Return the results
    return results

In [33]:
# TODO: Import the three supervised learning models from sklearn
from sklearn.linear_model import LogisticRegression, SGDClassifier
from sklearn.svm import LinearSVC, SVC
from sklearn.ensemble import AdaBoostClassifier, GradientBoostingClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier

# TODO: Initialize the three models
clf_A = LogisticRegression(C=10.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='newton-cg', tol=0.0001,
          verbose=0, warm_start=False)
clf_B = LinearSVC(random_state=101)
clf_C = GaussianNB()
clf_Ada = AdaBoostClassifier()
clf_Grad = GradientBoostingClassifier()
clf_KNN = KNeighborsClassifier()
clf_Dec = DecisionTreeClassifier()
clf_SGD = SGDClassifier()


# TODO: Calculate the number of samples for 1%, 10%, and 100% of the training data
n_train = len(y_train)
samples_1 = int(n_train * 0.01)
samples_10 = int(n_train * 0.1)
samples_100 = n_train

# Collect results on the learners
results = {}
for clf in [clf_A, clf_B, clf_C, clf_Ada, clf_Grad,clf_KNN ,clf_Dec, clf_SGD]:
    clf_name = clf.__class__.__name__
    results[clf_name] = {}
    for i, samples in enumerate([samples_1, samples_10, samples_100]):
        results[clf_name][i] = \
        train_predict(clf, samples, X_train, y_train, X_test, y_test)

/home/ubuntu/.local/lib/python3.5/site-packages/scipy/optimize/linesearch.py:414: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
/home/ubuntu/.local/lib/python3.5/site-packages/scipy/optimize/linesearch.py:285: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)

LogisticRegression trained on 1001 samples.
LogisticRegression trained on 10016 samples.
LogisticRegression trained on 100161 samples.
LinearSVC trained on 1001 samples.
LinearSVC trained on 10016 samples.
LinearSVC trained on 100161 samples.
GaussianNB trained on 1001 samples.
GaussianNB trained on 10016 samples.
GaussianNB trained on 100161 samples.
AdaBoostClassifier trained on 1001 samples.
AdaBoostClassifier trained on 10016 samples.
AdaBoostClassifier trained on 100161 samples.
GradientBoostingClassifier trained on 1001 samples.
GradientBoostingClassifier trained on 10016 samples.
GradientBoostingClassifier trained on 100161 samples.
KNeighborsClassifier trained on 1001 samples.
KNeighborsClassifier trained on 10016 samples.
KNeighborsClassifier trained on 100161 samples.
DecisionTreeClassifier trained on 1001 samples.
DecisionTreeClassifier trained on 10016 samples.
DecisionTreeClassifier trained on 100161 samples.
SGDClassifier trained on 1001 samples.
SGDClassifier trained on 10016 samples.
SGDClassifier trained on 100161 samples.

In [34]:
display(results)

# Run metrics visualization for the three supervised learning models chosen
#vs.evaluate(results, accuracy, fscore)

{'AdaBoostClassifier': {0: {'acc_test': 0.6561638912184018,
   'acc_train': 0.72227772227772225,
   'f_test': 0.70561391884237634,
   'f_train': 0.753735325506937,
   'pred_time': 0.16558218002319336,
   'train_time': 0.10762619972229004},
  1: {'acc_test': 0.67625094844455091,
   'acc_train': 0.67861421725239612,
   'f_test': 0.72218111949116037,
   'f_train': 0.72100793540303498,
   'pred_time': 0.21834158897399902,
   'train_time': 0.3888828754425049},
  2: {'acc_test': 0.67824767381494344,
   'acc_train': 0.67641097832489694,
   'f_test': 0.72218774159126309,
   'f_train': 0.72162996422840409,
   'pred_time': 0.7391140460968018,
   'train_time': 3.0757248401641846}},
 'DecisionTreeClassifier': {0: {'acc_test': 0.57693382852122521,
   'acc_train': 0.99200799200799206,
   'f_test': 0.65827268628840085,
   'f_train': 0.99742599742599736,
   'pred_time': 0.0032129287719726562,
   'train_time': 0.0058324337005615234},
  1: {'acc_test': 0.59889780759554334,
   'acc_train': 0.93620207667731625,
   'f_test': 0.67872996049791634,
   'f_train': 0.96627935041202628,
   'pred_time': 0.0069866180419921875,
   'train_time': 0.0637507438659668},
  2: {'acc_test': 0.63975080867377498,
   'acc_train': 0.80677109853136453,
   'f_test': 0.7102841660231155,
   'f_train': 0.84898990065081759,
   'pred_time': 0.03680157661437988,
   'train_time': 0.6392388343811035}},
 'GaussianNB': {0: {'acc_test': 0.67085978994449103,
   'acc_train': 0.68731268731268735,
   'f_test': 0.71505336298534794,
   'f_train': 0.73050213675213671,
   'pred_time': 0.005482673645019531,
   'train_time': 0.0013942718505859375},
  1: {'acc_test': 0.66758516033704729,
   'acc_train': 0.66134185303514381,
   'f_test': 0.71615431315193989,
   'f_train': 0.70878830818815797,
   'pred_time': 0.006966829299926758,
   'train_time': 0.004433870315551758},
  2: {'acc_test': 0.66778483287408652,
   'acc_train': 0.66505925460009385,
   'f_test': 0.71637701494845929,
   'f_train': 0.71527791228890603,
   'pred_time': 0.021765470504760742,
   'train_time': 0.03250861167907715}},
 'GradientBoostingClassifier': {0: {'acc_test': 0.65684277784433531,
   'acc_train': 0.79720279720279719,
   'f_test': 0.70764738568144436,
   'f_train': 0.80746187363834421,
   'pred_time': 0.03783893585205078,
   'train_time': 0.12417078018188477},
  1: {'acc_test': 0.67784832874086498,
   'acc_train': 0.69349041533546329,
   'f_test': 0.72239060739022454,
   'f_train': 0.72991898942743383,
   'pred_time': 0.048056840896606445,
   'train_time': 0.6858973503112793},
  2: {'acc_test': 0.68367876682241124,
   'acc_train': 0.6846676850271064,
   'f_test': 0.72335389089982693,
   'f_train': 0.72469753914394597,
   'pred_time': 0.16872787475585938,
   'train_time': 6.822776794433594}},
 'KNeighborsClassifier': {0: {'acc_test': 0.58120682081386521,
   'acc_train': 0.73126873126873126,
   'f_test': 0.65720644891595392,
   'f_train': 0.7662192393736017,
   'pred_time': 0.10916543006896973,
   'train_time': 0.0010046958923339844},
  1: {'acc_test': 0.608362285851204,
   'acc_train': 0.74191293929712465,
   'f_test': 0.67814226156415314,
   'f_train': 0.77305486100897192,
   'pred_time': 0.24680280685424805,
   'train_time': 0.007831573486328125},
  2: {'acc_test': 0.65796094405175509,
   'acc_train': 0.75006239953674581,
   'f_test': 0.71665449495372757,
   'f_train': 0.78658370274458334,
   'pred_time': 1.2177379131317139,
   'train_time': 0.1290757656097412}},
 'LinearSVC': {0: {'acc_test': 0.57905035741384125,
   'acc_train': 0.61338661338661338,
   'f_test': 0.65974487902864676,
   'f_train': 0.6923076923076924,
   'pred_time': 0.0009617805480957031,
   'train_time': 0.08993864059448242},
  1: {'acc_test': 0.61990335849207301,
   'acc_train': 0.60782747603833864,
   'f_test': 0.67966700878093278,
   'f_train': 0.66856459454540729,
   'pred_time': 0.0012183189392089844,
   'train_time': 1.0144848823547363},
  2: {'acc_test': 0.62022283455133576,
   'acc_train': 0.62219826080011187,
   'f_test': 0.67118661815135727,
   'f_train': 0.67277123050638132,
   'pred_time': 0.0037124156951904297,
   'train_time': 16.717629432678223}},
 'LogisticRegression': {0: {'acc_test': 0.65899924124435927,
   'acc_train': 0.69230769230769229,
   'f_test': 0.70888427731722414,
   'f_train': 0.7346609257265877,
   'pred_time': 0.000993490219116211,
   'train_time': 0.2613234519958496},
  1: {'acc_test': 0.66702607723333729,
   'acc_train': 0.66353833865814693,
   'f_test': 0.71269368994678539,
   'f_train': 0.7076347587394709,
   'pred_time': 0.0011532306671142578,
   'train_time': 0.674410343170166},
  2: {'acc_test': 0.6639910546703407,
   'acc_train': 0.66355168179231439,
   'f_test': 0.70959928387130744,
   'f_train': 0.71020182778454455,
   'pred_time': 0.003793954849243164,
   'train_time': 11.583117723464966}},
 'SGDClassifier': {0: {'acc_test': 0.38053592108941336,
   'acc_train': 0.37062937062937062,
   'f_test': 0.016905641475173754,
   'f_train': 0.015337423312883436,
   'pred_time': 0.0010039806365966797,
   'train_time': 0.0012128353118896484},
  1: {'acc_test': 0.3871251148117088,
   'acc_train': 0.39337060702875398,
   'f_test': 0.11669855151680784,
   'f_train': 0.11634310890816466,
   'pred_time': 0.0010933876037597656,
   'train_time': 0.008463859558105469},
  2: {'acc_test': 0.64350465237011301,
   'acc_train': 0.64222601611405639,
   'f_test': 0.70143457240231444,
   'f_train': 0.70122460773177042,
   'pred_time': 0.0033783912658691406,
   'train_time': 0.07991266250610352}}}

In [163]:
clf = GradientBoostingClassifier()

In [ ]:
# TODO: Import 'GridSearchCV', 'make_scorer', and any other necessary libraries
from sklearn.grid_search import GridSearchCV
from sklearn.metrics import make_scorer

# TODO: Initialize the classifier
clf = LogisticRegression()

# TODO: Create the parameters list you wish to tune
parameters = {'solver': ['newton-cg', 'lbfgs', 'sag'],
              'C': [0.01, 0.1, 1.0, 10.0, 100.0, 1000.0],
              'random_state': [None, 101, 20160101]}

# TODO: Make an fbeta_score scoring object
scorer = make_scorer(fbeta_score, beta=beta)

# TODO: Perform grid search on the classifier using 'scorer' as the scoring method
grid_obj = GridSearchCV(clf, parameters, scoring=scorer)

# TODO: Fit the grid search object to the training data and find the optimal parameters
grid_fit = grid_obj.fit(X_train, y_train)

# Get the estimator
best_clf = grid_fit.best_estimator_

# Make predictions using the unoptimized and model
predictions = (clf.fit(X_train, y_train)).predict(X_test)
best_predictions = best_clf.predict(X_test)

# Report the before-and-afterscores
print ("Unoptimized model\n------")
print ("Accuracy score on testing data: {:.4f}".format(accuracy_score(y_test, predictions)))
print ("F-score on testing data: {:.4f}".format(fbeta_score(y_test, predictions, beta = 0.5)))
print ("\nOptimized Model\n------")
print ("Final accuracy score on the testing data: {:.4f}".format(accuracy_score(y_test, best_predictions)))
print ("Final F-score on the testing data: {:.4f}".format(fbeta_score(y_test, best_predictions, beta = 0.5)))

# show best parameters
print ("\nBest Classifier\n------")
print (best_clf)

/home/ubuntu/.local/lib/python3.5/site-packages/scipy/optimize/linesearch.py:414: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
/home/ubuntu/.local/lib/python3.5/site-packages/scipy/optimize/linesearch.py:285: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
/home/ubuntu/.local/lib/python3.5/site-packages/sklearn/utils/optimize.py:195: UserWarning: Line Search failed
  warnings.warn('Line Search failed')
/home/ubuntu/.local/lib/python3.5/site-packages/scipy/optimize/linesearch.py:414: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
/home/ubuntu/.local/lib/python3.5/site-packages/scipy/optimize/linesearch.py:285: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
/home/ubuntu/.local/lib/python3.5/site-packages/sklearn/utils/optimize.py:195: UserWarning: Line Search failed
  warnings.warn('Line Search failed')
/home/ubuntu/.local/lib/python3.5/site-packages/scipy/optimize/linesearch.py:414: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
/home/ubuntu/.local/lib/python3.5/site-packages/scipy/optimize/linesearch.py:285: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
/home/ubuntu/.local/lib/python3.5/site-packages/sklearn/utils/optimize.py:195: UserWarning: Line Search failed
  warnings.warn('Line Search failed')
/home/ubuntu/.local/lib/python3.5/site-packages/sklearn/linear_model/sag.py:286: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)
/home/ubuntu/.local/lib/python3.5/site-packages/sklearn/linear_model/sag.py:286: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)
/home/ubuntu/.local/lib/python3.5/site-packages/sklearn/linear_model/sag.py:286: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)
/home/ubuntu/.local/lib/python3.5/site-packages/scipy/optimize/linesearch.py:414: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
/home/ubuntu/.local/lib/python3.5/site-packages/scipy/optimize/linesearch.py:285: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
/home/ubuntu/.local/lib/python3.5/site-packages/sklearn/utils/optimize.py:195: UserWarning: Line Search failed
  warnings.warn('Line Search failed')
/home/ubuntu/.local/lib/python3.5/site-packages/scipy/optimize/linesearch.py:414: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
/home/ubuntu/.local/lib/python3.5/site-packages/scipy/optimize/linesearch.py:285: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
/home/ubuntu/.local/lib/python3.5/site-packages/sklearn/utils/optimize.py:195: UserWarning: Line Search failed
  warnings.warn('Line Search failed')
/home/ubuntu/.local/lib/python3.5/site-packages/scipy/optimize/linesearch.py:414: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
/home/ubuntu/.local/lib/python3.5/site-packages/scipy/optimize/linesearch.py:285: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
/home/ubuntu/.local/lib/python3.5/site-packages/sklearn/utils/optimize.py:195: UserWarning: Line Search failed
  warnings.warn('Line Search failed')
/home/ubuntu/.local/lib/python3.5/site-packages/sklearn/linear_model/sag.py:286: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)
/home/ubuntu/.local/lib/python3.5/site-packages/sklearn/linear_model/sag.py:286: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)
/home/ubuntu/.local/lib/python3.5/site-packages/sklearn/linear_model/sag.py:286: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)
/home/ubuntu/.local/lib/python3.5/site-packages/scipy/optimize/linesearch.py:414: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
/home/ubuntu/.local/lib/python3.5/site-packages/scipy/optimize/linesearch.py:285: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
/home/ubuntu/.local/lib/python3.5/site-packages/sklearn/utils/optimize.py:195: UserWarning: Line Search failed
  warnings.warn('Line Search failed')
/home/ubuntu/.local/lib/python3.5/site-packages/scipy/optimize/linesearch.py:414: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
/home/ubuntu/.local/lib/python3.5/site-packages/scipy/optimize/linesearch.py:285: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
/home/ubuntu/.local/lib/python3.5/site-packages/sklearn/utils/optimize.py:195: UserWarning: Line Search failed
  warnings.warn('Line Search failed')
/home/ubuntu/.local/lib/python3.5/site-packages/scipy/optimize/linesearch.py:414: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
/home/ubuntu/.local/lib/python3.5/site-packages/scipy/optimize/linesearch.py:285: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
/home/ubuntu/.local/lib/python3.5/site-packages/sklearn/utils/optimize.py:195: UserWarning: Line Search failed
  warnings.warn('Line Search failed')
/home/ubuntu/.local/lib/python3.5/site-packages/sklearn/linear_model/sag.py:286: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)
/home/ubuntu/.local/lib/python3.5/site-packages/sklearn/linear_model/sag.py:286: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)
/home/ubuntu/.local/lib/python3.5/site-packages/sklearn/linear_model/sag.py:286: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)
/home/ubuntu/.local/lib/python3.5/site-packages/scipy/optimize/linesearch.py:414: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
/home/ubuntu/.local/lib/python3.5/site-packages/scipy/optimize/linesearch.py:285: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
/home/ubuntu/.local/lib/python3.5/site-packages/sklearn/utils/optimize.py:195: UserWarning: Line Search failed
  warnings.warn('Line Search failed')
/home/ubuntu/.local/lib/python3.5/site-packages/scipy/optimize/linesearch.py:414: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
/home/ubuntu/.local/lib/python3.5/site-packages/scipy/optimize/linesearch.py:285: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
/home/ubuntu/.local/lib/python3.5/site-packages/sklearn/utils/optimize.py:195: UserWarning: Line Search failed
  warnings.warn('Line Search failed')
/home/ubuntu/.local/lib/python3.5/site-packages/scipy/optimize/linesearch.py:414: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
/home/ubuntu/.local/lib/python3.5/site-packages/scipy/optimize/linesearch.py:285: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
/home/ubuntu/.local/lib/python3.5/site-packages/sklearn/utils/optimize.py:195: UserWarning: Line Search failed
  warnings.warn('Line Search failed')
/home/ubuntu/.local/lib/python3.5/site-packages/sklearn/linear_model/sag.py:286: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)
/home/ubuntu/.local/lib/python3.5/site-packages/sklearn/linear_model/sag.py:286: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)
/home/ubuntu/.local/lib/python3.5/site-packages/sklearn/linear_model/sag.py:286: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)
/home/ubuntu/.local/lib/python3.5/site-packages/scipy/optimize/linesearch.py:414: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
/home/ubuntu/.local/lib/python3.5/site-packages/scipy/optimize/linesearch.py:285: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
/home/ubuntu/.local/lib/python3.5/site-packages/sklearn/utils/optimize.py:195: UserWarning: Line Search failed
  warnings.warn('Line Search failed')
/home/ubuntu/.local/lib/python3.5/site-packages/scipy/optimize/linesearch.py:414: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
/home/ubuntu/.local/lib/python3.5/site-packages/scipy/optimize/linesearch.py:285: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
/home/ubuntu/.local/lib/python3.5/site-packages/sklearn/utils/optimize.py:195: UserWarning: Line Search failed
  warnings.warn('Line Search failed')
/home/ubuntu/.local/lib/python3.5/site-packages/scipy/optimize/linesearch.py:414: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
/home/ubuntu/.local/lib/python3.5/site-packages/scipy/optimize/linesearch.py:285: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
/home/ubuntu/.local/lib/python3.5/site-packages/sklearn/utils/optimize.py:195: UserWarning: Line Search failed
  warnings.warn('Line Search failed')
/home/ubuntu/.local/lib/python3.5/site-packages/sklearn/linear_model/sag.py:286: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)
/home/ubuntu/.local/lib/python3.5/site-packages/sklearn/linear_model/sag.py:286: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)
/home/ubuntu/.local/lib/python3.5/site-packages/sklearn/linear_model/sag.py:286: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)
/home/ubuntu/.local/lib/python3.5/site-packages/scipy/optimize/linesearch.py:414: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
/home/ubuntu/.local/lib/python3.5/site-packages/scipy/optimize/linesearch.py:285: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
/home/ubuntu/.local/lib/python3.5/site-packages/sklearn/utils/optimize.py:195: UserWarning: Line Search failed
  warnings.warn('Line Search failed')
/home/ubuntu/.local/lib/python3.5/site-packages/scipy/optimize/linesearch.py:414: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
/home/ubuntu/.local/lib/python3.5/site-packages/scipy/optimize/linesearch.py:285: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
/home/ubuntu/.local/lib/python3.5/site-packages/sklearn/utils/optimize.py:195: UserWarning: Line Search failed
  warnings.warn('Line Search failed')
/home/ubuntu/.local/lib/python3.5/site-packages/scipy/optimize/linesearch.py:414: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
/home/ubuntu/.local/lib/python3.5/site-packages/scipy/optimize/linesearch.py:285: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
/home/ubuntu/.local/lib/python3.5/site-packages/sklearn/utils/optimize.py:195: UserWarning: Line Search failed
  warnings.warn('Line Search failed')
/home/ubuntu/.local/lib/python3.5/site-packages/sklearn/linear_model/sag.py:286: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)
/home/ubuntu/.local/lib/python3.5/site-packages/sklearn/linear_model/sag.py:286: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)
/home/ubuntu/.local/lib/python3.5/site-packages/sklearn/linear_model/sag.py:286: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)
/home/ubuntu/.local/lib/python3.5/site-packages/scipy/optimize/linesearch.py:414: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
/home/ubuntu/.local/lib/python3.5/site-packages/scipy/optimize/linesearch.py:285: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
/home/ubuntu/.local/lib/python3.5/site-packages/sklearn/utils/optimize.py:195: UserWarning: Line Search failed
  warnings.warn('Line Search failed')
/home/ubuntu/.local/lib/python3.5/site-packages/scipy/optimize/linesearch.py:414: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
/home/ubuntu/.local/lib/python3.5/site-packages/scipy/optimize/linesearch.py:285: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
/home/ubuntu/.local/lib/python3.5/site-packages/sklearn/utils/optimize.py:195: UserWarning: Line Search failed
  warnings.warn('Line Search failed')
/home/ubuntu/.local/lib/python3.5/site-packages/scipy/optimize/linesearch.py:414: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
/home/ubuntu/.local/lib/python3.5/site-packages/scipy/optimize/linesearch.py:285: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
/home/ubuntu/.local/lib/python3.5/site-packages/scipy/optimize/linesearch.py:414: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
/home/ubuntu/.local/lib/python3.5/site-packages/scipy/optimize/linesearch.py:285: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
/home/ubuntu/.local/lib/python3.5/site-packages/sklearn/utils/optimize.py:195: UserWarning: Line Search failed
  warnings.warn('Line Search failed')
/home/ubuntu/.local/lib/python3.5/site-packages/sklearn/linear_model/sag.py:286: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)
/home/ubuntu/.local/lib/python3.5/site-packages/sklearn/linear_model/sag.py:286: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)
/home/ubuntu/.local/lib/python3.5/site-packages/sklearn/linear_model/sag.py:286: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)
/home/ubuntu/.local/lib/python3.5/site-packages/scipy/optimize/linesearch.py:414: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
/home/ubuntu/.local/lib/python3.5/site-packages/scipy/optimize/linesearch.py:285: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
/home/ubuntu/.local/lib/python3.5/site-packages/sklearn/utils/optimize.py:195: UserWarning: Line Search failed
  warnings.warn('Line Search failed')
/home/ubuntu/.local/lib/python3.5/site-packages/scipy/optimize/linesearch.py:414: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
/home/ubuntu/.local/lib/python3.5/site-packages/scipy/optimize/linesearch.py:285: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
/home/ubuntu/.local/lib/python3.5/site-packages/sklearn/utils/optimize.py:195: UserWarning: Line Search failed
  warnings.warn('Line Search failed')
/home/ubuntu/.local/lib/python3.5/site-packages/scipy/optimize/linesearch.py:414: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
/home/ubuntu/.local/lib/python3.5/site-packages/scipy/optimize/linesearch.py:285: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
/home/ubuntu/.local/lib/python3.5/site-packages/sklearn/utils/optimize.py:195: UserWarning: Line Search failed
  warnings.warn('Line Search failed')
/home/ubuntu/.local/lib/python3.5/site-packages/sklearn/linear_model/sag.py:286: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)
/home/ubuntu/.local/lib/python3.5/site-packages/sklearn/linear_model/sag.py:286: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)
/home/ubuntu/.local/lib/python3.5/site-packages/sklearn/linear_model/sag.py:286: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)
/home/ubuntu/.local/lib/python3.5/site-packages/scipy/optimize/linesearch.py:414: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
/home/ubuntu/.local/lib/python3.5/site-packages/scipy/optimize/linesearch.py:285: LineSearchWarning: The line search algorithm did not converge

Unoptimized model
------
Accuracy score on testing data: 0.6597
F-score on testing data: 0.7063

Optimized Model
------
Final accuracy score on the testing data: 0.6640
Final F-score on the testing data: 0.7096

Best Classifier
------
LogisticRegression(C=10.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='newton-cg', tol=0.0001,
          verbose=0, warm_start=False)

In [35]:
from sklearn.externals import joblib

best_clf= clf_A
filename = 'logistic_regression_best_invesco.joblib.pkl'

_ = joblib.dump(best_clf, filename, compress=9)

In [36]:
print(best_clf)

clf_loaded = joblib.load(filename)

print(clf_loaded)

LogisticRegression(C=10.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='newton-cg', tol=0.0001,
          verbose=0, warm_start=False)
LogisticRegression(C=10.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='newton-cg', tol=0.0001,
          verbose=0, warm_start=False)

In [37]:


pred = clf_loaded.predict(test_raw)
pred_prob = clf_loaded.predict_proba(test_raw)

In [38]:
pred_prob[:,1]

array([ 0.98739568,  0.66830785,  0.28366529, ...,  0.96911992,
        0.98753347,  0.95601119])

In [39]:
pred_prob = pd.DataFrame(pred_prob[:,1],columns=["Propensity_Score"])
pred_prob.head()

   Propensity_Score
0          0.987396
1          0.668308
2          0.283665
3          0.872148
4          0.662870

In [40]:
pred_df= pd.DataFrame(pred,columns=["Redeem_Status"])

pred_df=pred_df.replace([0,1],['NO','YES'])
pred_df.head()

pred_df['Redeem_Status'].value_counts()

YES    8390
NO      324
Name: Redeem_Status, dtype: int64

In [41]:
result = pd.concat([test_df, pred_prob, pred_df], axis=1)

result.head()

   Unique_Advisor_Id  Unique_Investment_Id  Propensity_Score Redeem_Status
0            1000103                 14147          0.987396           YES
1            1000103                  3534          0.668308           YES
2            1000103                  3651          0.283665            NO
3            1000103                  7668          0.872148           YES
4            1000103                  9339          0.662870           YES

In [47]:
result.to_csv('test_data_v2-2.csv',index=False)